version: '3.8'

services:
  backend:
    build: ./portfolio_be
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    # Make sure the Firebase credentials file exists in the correct directory
    volumes:
      - ./portfolio_be/src/main/resources:/app/src/main/resources

  frontend:
    build: ./portfolio-fe
    ports:
      - "3000:80"
    depends_on:
      - backend  # Ensure backend starts first
    entrypoint: /bin/sh -c "until nc -z backend 8080; do echo waiting for backend; sleep 3; done; npm start"
