services:
  backend:
    build: ./portfolio_be
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build: ./portfolio-fe
    ports:
      - "3000:80"
    depends_on:
      - backend  # Only the frontend depends on the backend
